### ISSUE TITLE
BUG one of my themes can't be loaded anymore and I don't know how to fix it

### ISSUE THREAD

**Issue by bernatagulloesbrina** [PowerBI-tips/tools#15]
Hello, 
when trying to load the BX Theme now I'm getting the following error 
I checked for the title background and looks fine -- I even reseted the property, but the error persists 

I guess I'l lhave to create a new theme, but hopefully this will not happen again

#/visualStyles/tableEx/*/title/0/background/solid/color must be string (type; matching schema #/definitions/color/type)
#/visualStyles/tableEx/*/title/0/background/solid/color must have required property 'expr' (required; matching schema #/definitions/themeDataColor/required)
#/visualStyles/tableEx/*/title/0/background/solid/color must NOT have additional properties (additionalProperties; matching schema #/definitions/themeDataColor/additionalProperties)
#/visualStyles/tableEx/*/title/0/background/solid/color must match exactly one schema in oneOf (oneOf; matching schema #/oneOf/0/properties/solid/properties/color/oneOf)
#/visualStyles/tableEx/*/title/0/background must have required property 'gradient' (required; matching schema #/oneOf/1/required)
#/visualStyles/tableEx/*/title/0/background must NOT have additional properties (additionalProperties; matching schema #/oneOf/1/additionalProperties)
#/visualStyles/tableEx/*/title/0/background must have required property 'pattern' (required; matching schema #/oneOf/2/required)
#/visualStyles/tableEx/*/title/0/background must NOT have additional properties (additionalProperties; matching schema #/oneOf/2/additionalProperties)
#/visualStyles/tableEx/*/title/0/background must match exactly one schema in oneOf (oneOf; matching schema #/oneOf)
#/visualStyles/tableEx/*/values/0/fontColorPrimary/solid/color must be string (type; matching schema #/definitions/color/type)
#/visualStyles/tableEx/*/values/0/fontColorPrimary/solid/color must have required property 'expr' (required; matching schema #/definitions/themeDataColor/required)
#/visualStyles/tableEx/*/values/0/fontColorPrimary/solid/color must NOT have additional properties (additionalProperties; matching schema #/definitions/themeDataColor/additionalProperties)
#/visualStyles/tableEx/*/values/0/fontColorPrimary/solid/color must match exactly one schema in oneOf (oneOf; matching schema #/oneOf/0/properties/solid/properties/color/oneOf)
#/visualStyles/tableEx/*/values/0/fontColorPrimary must have required property 'gradient' (required; matching schema #/oneOf/1/required)
#/visualStyles/tableEx/*/values/0/fontColorPrimary must NOT have additional properties (additionalProperties; matching schema #/oneOf/1/additionalProperties)
#/visualStyles/tableEx/*/values/0/fontColorPrimary must have required property 'pattern' (required; matching schema #/oneOf/2/required)
#/visualStyles/tableEx/*/values/0/fontColorPrimary must NOT have additional properties (additionalProperties; matching schema #/oneOf/2/additionalProperties)
#/visualStyles/tableEx/*/values/0/fontColorPrimary must match exactly one schema in oneOf (oneOf; matching schema #/oneOf)
#/visualStyles/tableEx/*/values/0/backColorPrimary/solid/color must be string (type; matching schema #/definitions/color/type)
#/visualStyles/tableEx/*/values/0/backColorPrimary/solid/color must have required property 'expr' (required; matching schema #/definitions/themeDataColor/required)
#/visualStyles/tableEx/*/values/0/backColorPrimary/solid/color must NOT have additional properties (additionalProperties; matching schema #/definitions/themeDataColor/additionalProperties)
#/visualStyles/tableEx/*/values/0/backColorPrimary/solid/color must match exactly one schema in oneOf (oneOf; matching schema #/oneOf/0/properties/solid/properties/color/oneOf)
#/visualStyles/tableEx/*/values/0/backColorPrimary must have required property 'gradient' (required; matching schema #/oneOf/1/required)
#/visualStyles/tableEx/*/values/0/backColorPrimary must NOT have additional properties (additionalProperties; matching schema #/oneOf/1/additionalProperties)
#/visualStyles/tableEx/*/values/0/backColorPrimary must have required property 'pattern' (required; matching schema #/oneOf/2/required)
#/visualStyles/tableEx/*/values/0/backColorPrimary must NOT have additional properties (additionalProperties; matching schema #/oneOf/2/additionalProperties)
#/visualStyles/tableEx/*/values/0/backColorPrimary must match exactly one schema in oneOf (oneOf; matching schema #/oneOf)
#/visualStyles/tableEx/*/values/0/fontColorSecondary/solid/color must be string (type; matching schema #/definitions/color/type)
#/visualStyles/tableEx/*/values/0/fontColorSecondary/solid/color must have required property 'expr' (required; matching schema #/definitions/themeDataColor/required)
#/visualStyles/tableEx/*/values/0/fontColorSecondary/solid/color must NOT have additional properties (additionalProperties; matching schema #/definitions/themeDataColor/additionalProperties)
#/visualStyles/tableEx/*/values/0/fontColorSecondary/solid/color must match exactly one schema in oneOf (oneOf; matching schema #/oneOf/0/properties/solid/properties/color/oneOf)
#/visualStyles/tableEx/*/values/0/fontColorSecondary must have required property 'gradient' (required; matching schema #/oneOf/1/required)
#/visualStyles/tableEx/*/values/0/fontColorSecondary must NOT have additional properties (additionalProperties; matching schema #/oneOf/1/additionalProperties)
#/visualStyles/tableEx/*/values/0/fontColorSecondary must have required property 'pattern' (required; matching schema #/oneOf/2/required)
#/visualStyles/tableEx/*/values/0/fontColorSecondary must NOT have additional properties (additionalProperties; matching schema #/oneOf/2/additionalProperties)
#/visualStyles/tableEx/*/values/0/fontColorSecondary must match exactly one schema in oneOf (oneOf; matching schema #/oneOf)
#/visualStyles/tableEx/*/values/0/backColorSecondary/solid/color must be string (type; matching schema #/definitions/color/type)
#/visualStyles/tableEx/*/values/0/backColorSecondary/solid/color must have required property 'expr' (required; matching schema #/definitions/themeDataColor/required)
#/visualStyles/tableEx/*/values/0/backColorSecondary/solid/color must NOT have additional properties (additionalProperties; matching schema #/definitions/themeDataColor/additionalProperties)
#/visualStyles/tableEx/*/values/0/backColorSecondary/solid/color must match exactly one schema in oneOf (oneOf; matching schema #/oneOf/0/properties/solid/properties/color/oneOf)
#/visualStyles/tableEx/*/values/0/backColorSecondary must have required property 'gradient' (required; matching schema #/oneOf/1/required)
#/visualStyles/tableEx/*/values/0/backColorSecondary must NOT have additional properties (additionalProperties; matching schema #/oneOf/1/additionalProperties)
#/visualStyles/tableEx/*/values/0/backColorSecondary must have required property 'pattern' (required; matching schema #/oneOf/2/required)
#/visualStyles/tableEx/*/values/0/backColorSecondary must NOT have additional properties (additionalProperties; matching schema #/oneOf/2/additionalProperties)
#/visualStyles/tableEx/*/values/0/backColorSecondary must match exactly one schema in oneOf (oneOf; matching schema #/oneOf)
#/visualStyles/pivotTable/*/title/0/background/solid/color must be string (type; matching schema #/definitions/color/type)
#/visualStyles/pivotTable/*/title/0/background/solid/color must have required property 'expr' (required; matching schema #/definitions/themeDataColor/required)
#/visualStyles/pivotTable/*/title/0/background/solid/color must NOT have additional properties (additionalProperties; matching schema #/definitions/themeDataColor/additionalProperties)
#/visualStyles/pivotTable/*/title/0/background/solid/color must match exactly one schema in oneOf (oneOf; matching schema #/oneOf/0/properties/solid/properties/color/oneOf)
#/visualStyles/pivotTable/*/title/0/background must have required property 'gradient' (required; matching schema #/oneOf/1/required)
#/visualStyles/pivotTable/*/title/0/background must NOT have additional properties (additionalProperties; matching schema #/oneOf/1/additionalProperties)
#/visualStyles/pivotTable/*/title/0/background must have required property 'pattern' (required; matching schema #/oneOf/2/required)
#/visualStyles/pivotTable/*/title/0/background must NOT have additional properties (additionalProperties; matching schema #/oneOf/2/additionalProperties)
#/visualStyles/pivotTable/*/title/0/background must match exactly one schema in oneOf (oneOf; matching schema #/oneOf)

**Comment by Braden-CHEP** [comment]
**I can help with this as it is also a problem for me.** 

What's happened is the saved theme has forgotten the selected color for the field items notated. If you follow the hierarchy of each line item, you'll find this below as an example:

#/visualStyles/tableEx//values/0/fontColorPrimary must match exactly one schema in oneOf (oneOf; matching schema #/oneOf)

1. Breaking it down left to right, there is an error with the Table group of fields. 
2. The specific field is "Values."
3. The issue with Values has to do with the font color.
4. If you go into this exact field using the tool, I'll bet money that the selection is blank now when it had a selection before. 

In my case, the saved theme forgets all of the problem settings _on every sign-in/session_. Very frustrating.

**Comment by MikeCarlo** [comment]
@bernatagulloesbrina can you add the json file that broke?

**Comment by bernatagulloesbrina** [comment]
[BX Theme(1).zip](https://github.com/PowerBI-tips/tools/files/11371454/BX.Theme.1.zip)
had to zip it to upload
I think that at some point some properties of the table that have been set switch to unset and that leaves an inconsistent theme

**Comment by Braden-CHEP** [comment]
Fix looks good to me so far. Thanks @ethanmaurer @MikeCarlo
