### ISSUE TITLE
Canvas (page) Settings not working

### ISSUE THREAD

**Issue by KNP-BI** [PowerBI-tips/tools#35]
This may be a Power BI Desktop issue, but nothing I change in the canvas settings for the page is applying when using the theme.
For example, I changed to custom, 1920, 1080 but after successfully applying the theme to a file, the settings remain as 16:9, 1280, 720.

**Comment by MikeCarlo** [comment]
We have issued updates and are working on #51 to the newer PBIP format that Microsoft is changing.  This should be resolve when the work for #51 is complete.
