### ISSUE TITLE
BUG:  Card (New) Theme Properties not being applied to Visual 

### ISSUE THREAD

**Issue by jmazzanti-dm** [PowerBI-tips/tools#37]
The following theme properties are not applying correctly to visual: 

Visual: Card (New) 
Properties: 
Title: Show 
Title: Font Color 
Layout: Columns 
Layout: Orientation 
Layout: Rows
Layout: Space between cards

**Comment by MikeCarlo** [comment]
We have updated the app to resolve these issues now, 

Please see #44 for resolution to common challenges with desktop overriding the theme file.
