### ISSUE TITLE
BUG: Slicer -> Slicer Settings -> Options -> Style is missing from Theme Generator

### ISSUE THREAD

**Issue by jmazzanti-dm** [PowerBI-tips/tools#38]
I cannot set the Slicer Style via Theme Generator. 
Options:  Dropdown | Vertical List | Tile 

When I search properties of the Visual, a header comes back "Style" but there are no properties. 
When clear my search, there is no heading called "Style".... so it's kind of in there, but not really.

**Comment by KNP-BI** [comment]
I have the same problem with the table and matrix when trying to set the style and it is currently preventing me from using the generator to build a theme. Need this fixed ASAP.

**Comment by KNP-BI** [comment]
Some additional, potentially related questions...

1. Should there be a lot more settings in here?
2. Why are the 'General' and 'General Advanced' settings identical?
3. If this can't be fixed quickly, does anyone know the correct JSON to set as 'Dropdown' and to turn off 'Multi-select using ctrl'?

![image](https://github.com/PowerBI-tips/tools/assets/73139861/0c0bc989-646e-438a-86bc-ec4ecd536b6a)

**Comment by MikeCarlo** [comment]
I think what you are looking for is found under the Data section for Style:

![image](https://github.com/user-attachments/assets/c90c4670-ebea-4648-83eb-064174f52678)

this will produce the desired data mode

``` json
{
	"name": "My New Theme",
	"visualStyles": {
		"slicer": {
			"*": {
				"data": [
					{
						"mode": "VerticalList"
					}
				]
			}
		}
	}
}
```

**Comment by MikeCarlo** [comment]
Multi-select is found in this section of code
![image](https://github.com/user-attachments/assets/6e8dfeef-a37f-450e-8c7f-50c42b8f93da)

```json
{
	"name": "My New Theme",
	"visualStyles": {
		"slicer": {
			"*": {
				"selection": [
					{
						"singleSelect": true
					}
				]
			}
		}
	}
}
```
