### ISSUE TITLE
MS Authentication with Multiple MS Accounts

### ISSUE THREAD

**Issue by jahampeldvm** [PowerBI-tips/tools#40]
I need a little help here. I have a work MS account and a personal account. My themes subscription is linked to my personal account. If I'm already logged in to my computer with my work MS account and try to log in to themes, it assumes I want to use my work account and asks me to sign up for a plan. How do I sign in with my personal account if I'm already logged in to my machine with my work account?

**Comment by ryanbyk** [comment]
@jahampeldvm 

Couple options:
1. You could sign out of microsoft in your browser by going to Microsoft account site, like office and selecting logout from your account menu.  
2. You could create a profile in your browser for your personal account based items and work based accounts.  Im not sure what browser you use, but this can be done in edge and chrome.  

### Edge
![image](https://github.com/PowerBI-tips/tools/assets/2565553/33013ca5-2efe-4968-8e57-480bf203db35)

### Chrome
![image](https://github.com/PowerBI-tips/tools/assets/2565553/743031e1-869d-4339-86c2-9703acb0676d)

**Comment by jahampeldvm** [comment]
Thanks for the help. The first option worked, the second option did not.
