### ISSUE TITLE
The theme does not change the visual properties

### ISSUE THREAD

**Issue by CheenuSing** [PowerBI-tips/tools#44]
I created parameter for the Card visual to choose Calibri for Data lables and text size 27. 
When applying the theme the card visual shows as Arial.

**Comment by MikeCarlo** [comment]
make sure you check that the visual inside desktop is not overriding the properties of the theme file.

 if this Reset to Default item is greyed out then the visual
![image](https://github.com/user-attachments/assets/1db76c46-5d23-48f2-8d11-d870da7d6404)

However if you have overridden the visual the item "Reset to Default" will have a darker color. 
![image](https://github.com/user-attachments/assets/88e50ed5-6b1c-4839-a724-7c30616e2b43)

The visual properties of desktop will override the theme files.
