### ISSUE TITLE
Downloaded PBIP files are unable to save and upgrade to new TMDL / PBIR formats

### ISSUE THREAD

**Issue by PBIQueryous** [PowerBI-tips/tools#48]
If you download the pbip project file, and then try to save and upgrade to the new TMDL and PBIR preview features, it returns and error citing the file path is not valid. The only way out is to quit without saving and lose any changes.

<img width="488" alt="image" src="https://github.com/user-attachments/assets/c4ad16df-c61a-426a-9b7f-ed285826c38c">

**Comment by MikeCarlo** [comment]
We are aware of this issue.  Microsoft has since changed the file format of PBIP projects. And thus, we are updating our Download of PBIP formats to match what Microsoft is changing in this space.

**Comment by MikeCarlo** [comment]
Issue #51 will resolve this. Added to backlog.

**Comment by MikeCarlo** [comment]
updating to the new PBIP format will by default enable TMDL and PBIR Formats.

We will be tracking this issue on #51 and closing out this issue
