### ISSUE TITLE
Page turns blank once clicked on any dropdowns

### ISSUE THREAD

**Issue by dezaidamalek** [PowerBI-tips/tools#49]
Hi, I just recently subscribed for Tips+ and created a theme file. When I want to click any dropdown in any tabs to edit my existing theme file, the page will turn blank (image attached below) The power bi preview on right side is also not working properly, it keeps loading.
![image](https://github.com/user-attachments/assets/75d2cfd8-f4cf-48af-b284-8c95f4704fbd)

However, the pages are working normally with free plan. Need quick assistance as I'm developing the theme for my company and they need it quick. Thank you!

**Comment by ryanbyk** [comment]
Hey there @dezaidamalek, do you experience this in chrome?

Just want to confirm some repro steps, you are selecting an existing theme that you have created and attempting to edit the theme.  When you go to the text properties, the page shows up and you try to set the title style, or a property and the page goes blank?

Another question:
Is it just one theme causing issues or are you seeing this on all of your user themes?

I'm not seeing this using my account with a theme that I have prerviously created.

**Comment by MikeCarlo** [comment]
I believe this was an issue when previewing the report page when on the themes colors page. This issue has been addressed and fixed.
