### ISSUE TITLE
Drill Through Issue from PBIP file

### ISSUE THREAD

**Issue by amar-khaliq** [PowerBI-tips/tools#50]
I cannot drill through from a matrix visual to a table visual on a different page. I spent all morning testing it to see what the issue was and concluded that it was coming from the PBIP file generated by the theme generator. So I used a blank file and a PBIP file, did the same actions from the blank PBIX file, and managed to drill through on the sample data, and the PBIP file from the theme generator could not drill through. I am very disappointed with this. I spent all morning trying to find this bug and had to spend money on the subscription. More detail on the bug: When you add a measure to the drill-through page, the keep filters button greys out.

**Comment by MikeCarlo** [comment]
Issue #51 will resolve this.

Added to toDo

**Comment by MikeCarlo** [comment]
I've been able to replicate this issue.  This is due to the change in Microsoft spec for PBIP format which is currently in preview. We are adding to our backlog to update our PBIP format to match the development of Microsoft. Closing this issue and tracking on #51
