### ISSUE TITLE
Bug - Duplicate Property Names Shown and No Help To What is It Tied Too

### ISSUE THREAD

**Issue by pugliathomas** [PowerBI-tips/tools#6]
Many of the Global Level Properties have the same Property Name despite being tied to a higher level object. However in the Global settings there is no way to tell what the object a property is tied too. 

This is a two part issue. 

## Issue 1 - Duplicate Name of Property despite being binded to other different objects. 

The following show up twice in Global but have different config:

1. Analysis
2. Bubbles
3. Grid Layout
4. Header
5. Heat map
6. Page Alignment
7. Values

**Comment by MikeCarlo** [comment]
as designed, Microsoft has not adjusted their spec to reflect the naming
